/**
 * Конфигурация Firebase и константы приложения.
 * Здесь описывается экономика, способности, погода и локализация.
 */

// В продакшене ADMIN_IDS лучше прокидывать из back-end / env,
// но для Mini App читаем их статически. Значения должны совпадать с Telegram ID.
export const ADMIN_IDS = [6250975346];

export const FIREBASE_CONFIG = {
    apiKey: "AIzaSyBzu_EqbYoHR9AGRjNTjlCX2f4seIMgpwk",
    authDomain: "test-game-bf099.firebaseapp.com",
    databaseURL: "https://test-game-bf099-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "test-game-bf099",
    storageBucket: "test-game-bf099.firebasestorage.app",
    messagingSenderId: "624705252854",
    appId: "1:624705252854:web:f24eb7255da54c47902bd7",
    measurementId: "G-TVDRXT9CHV"
};

// Игровое поле
export const GRID_SIZE = 10;
export const SHIP_SIZES = [4, 3, 3, 2, 2, 2, 1, 1, 1, 1];

// Экономика и рейтинг
export const ECONOMY = {
    START_RATING: 1000,
    START_COINS: 50,
    RANKED_WIN_RATING_DELTA: 25,
    RANKED_LOSS_RATING_DELTA: -25,
    MIN_RATING_FOR_RANKED: 25, // Минимальный рейтинг для создания ranked-игры
    MIN_RATING: 25,
    RANKED_WIN_COINS: 50,
    RANKED_LOSS_COINS: 25
};

// Способности и их стоимость (монеты)
export const ABILITIES = {
    scout:       { id: 'scout',       cost: 40 },
    sonar:       { id: 'sonar',       cost: 60 },
    doubleShot:  { id: 'doubleShot',  cost: 75 },
    decoy:       { id: 'decoy',       cost: 50 },
    radar:       { id: 'radar',       cost: 70 },
    overheat:    { id: 'overheat',    cost: 120 },
    fog:         { id: 'fog',         cost: 80 },
    counterStrike: { id: 'counterStrike', cost: 95 }
};

export const WEATHER_TYPES = ['calm', 'storm', 'night'];

export const TEXTS = {
    en: {
        app_title: "NAVAL WARFARE",
        lang_en: "English",
        lang_ru: "Russian",
        welcome: "Welcome, Commander",
        deploy: "DEPLOY",
        create_battle: "CREATE BATTLE (FRIEND)",
        play_random: "RANKED RANDOM",
        shop: "SHOP",
        dashboard_command: "COMMAND",
        stats_coins: "Coins",
        stats_wins: "Wins",
        stats_winrate: "WinRate",
        share_link_label: "Send this link to friend:",
        share_link_copy: "COPY",
        deploy_fleet: "Deploy Fleet",
        select_ship: "Select Ship:",
        ready: "READY FOR BATTLE",
        waiting: "Waiting for opponent...",
        your_turn: "YOUR TURN",
        enemy_turn: "ENEMY TURN",
        nick_placeholder: "Nickname...",
        back: "Back",
        opponent_left: "Opponent left the game",
        battle_you: "YOU",
        battle_enemy: "ENEMY",
        battle_alive: "ALIVE",
        battle_waiting: "WAITING...",
        battle_enemy_waters: "ENEMY WATERS",
        battle_your_fleet: "YOUR FLEET",
        admin_panel_button: "ADMIN PANEL",
        admin_title: "ADMIN",
        admin_active_games: "Active Games",
        admin_user_id_placeholder: "User ID",
        admin_amount_placeholder: "Amount",
        admin_add_coins: "Add Coins",
        admin_add_gems: "Add Gems",
        admin_tab_overview: "Overview",
        admin_tab_matches: "Matches",
        admin_tab_bans: "Bans",
        admin_tab_logs: "Logs",
        admin_ban: "BAN",
        admin_unban: "UNBAN",
        admin_ban_reason: "Reason",
        admin_total_games: "Total Games",
        admin_human_wins: "Human Wins",
        admin_bot_wins: "Bot Wins",
        admin_activity_title: "Activity (last 24h)",
        admin_recent_matches: "Recent Matches",
        admin_logs_title: "Admin Logs",
        admin_view_profile: "View Profile",
        admin_matches: "matches",
        admin_no_reason: "no reason",
        shop_title: "TACTICAL ABILITIES",
        ability_scout_title: "SCOUT",
        ability_scout_desc: "Open 1 cell",
        ability_scout_price: "40 coins",
        ability_sonar_title: "SONAR",
        ability_sonar_desc: "Scan 3x3 area",
        ability_sonar_price: "60 coins",
        ability_doubleShot_title: "DOUBLE SHOT",
        ability_doubleShot_desc: "Two shots in a row",
        ability_doubleShot_price: "75 coins",
        ability_decoy_title: "DECOY",
        ability_decoy_desc: "Next enemy shot misses",
        ability_decoy_price: "50 coins",
        ability_radar_title: "RADAR",
        ability_radar_desc: "Block repeated cells",
        ability_radar_price: "70 coins",
        ability_overheat_title: "OVERHEAT",
        ability_overheat_desc: "Enemy skips a turn",
        ability_overheat_price: "120 coins",
        ability_fog_title: "FOG",
        ability_fog_desc: "Hide part of field",
        ability_fog_price: "80 coins",
        ability_counterStrike_title: "COUNTER STRIKE",
        ability_counterStrike_desc: "Return shot on hit",
        ability_counterStrike_price: "95 coins",
        settings_title: "SETTINGS",
        settings_lang_en: "English",
        settings_lang_ru: "Russian",
        error_save_user: "Save failed. Check connection and reopen the app.",
        error_create_battle: "Failed to create battle. Check your connection.",
        error_matchmaking: "Matchmaking failed. Try again.",
        match_finished: "Match finished",
        admin_done: "Done!",
        shop_purchased: "Purchased",
        shop_purchase_failed: "Purchase failed",
        matchmaking_search_title: "Searching for opponent...",
        matchmaking_search_sub: "We will find a fair enemy or start a bot battle.",
        matchmaking_cancel: "CANCEL",
        matchmaking_vs_bot_easy: "You will fight bot (easy).",
        matchmaking_vs_bot_normal: "You will fight bot (normal).",
        matchmaking_vs_bot_hard: "You will fight bot (hard).",
        lb_title: "LEADERBOARDS",
        lb_tab_rating: "Rating",
        lb_tab_winrate: "Winrate 30+",
        lb_tab_games: "Games",
        onboarding_slide1_title: "FLEET PLACEMENT",
        onboarding_slide1_text: "Place your ships on the board. Tap a ship to rotate it. When all ships are placed, press \"READY\".",
        onboarding_slide2_title: "TACTICAL ABILITIES",
        onboarding_slide2_text: "Buy abilities in the shop for coins. Use them in battle for advantages: scout, double shot, fog, and more.",
        onboarding_slide3_title: "RATING & ECONOMY",
        onboarding_slide3_text: "Win matches to increase rating and earn coins. Lose to decrease rating. Higher rating means stronger opponents.",
        onboarding_next: "NEXT",
        onboarding_skip: "SKIP",
        onboarding_start: "START",
        error_low_rating: "Your rating is too low for ranked matches. Minimum rating: 25",
        error_low_rating_title: "Rating Too Low"
    },
    ru: {
        app_title: "МОРСКОЙ БОЙ",
        lang_en: "Английский",
        lang_ru: "Русский",
        welcome: "Добро пожаловать",
        deploy: "В БОЙ",
        create_battle: "БИТВА С ДРУГОМ",
        play_random: "РЕЙТИНГОВЫЙ РАНДОМ",
        shop: "МАГАЗИН",
        dashboard_command: "КОМАНДОВАНИЕ",
        stats_coins: "Монеты",
        stats_wins: "Победы",
        stats_winrate: "Винрейт",
        share_link_label: "Отправьте эту ссылку другу:",
        share_link_copy: "СКОПИРОВАТЬ",
        deploy_fleet: "Расстановка",
        select_ship: "Выберите корабль:",
        ready: "К БОЮ",
        waiting: "Ждем противника...",
        your_turn: "ВАШ ХОД",
        enemy_turn: "ХОД ВРАГА",
        nick_placeholder: "Ник...",
        back: "Назад",
        opponent_left: "Противник вышел из игры",
        battle_you: "ВЫ",
        battle_enemy: "ВРАГ",
        battle_alive: "В СТРОЮ",
        battle_waiting: "ОЖИДАНИЕ...",
        battle_enemy_waters: "ВОДЫ ПРОТИВНИКА",
        battle_your_fleet: "ВАШ ФЛОТ",
        admin_panel_button: "АДМИН-ПАНЕЛЬ",
        admin_title: "АДМИН",
        admin_active_games: "Активные игры",
        admin_user_id_placeholder: "ID игрока",
        admin_amount_placeholder: "Сумма",
        admin_add_coins: "Добавить монеты",
        admin_add_gems: "Добавить гемы",
        admin_tab_overview: "Обзор",
        admin_tab_matches: "Матчи",
        admin_tab_bans: "Баны",
        admin_tab_logs: "Логи",
        admin_ban: "ЗАБАНИТЬ",
        admin_unban: "РАЗБАНИТЬ",
        admin_ban_reason: "Причина",
        admin_total_games: "Всего игр",
        admin_human_wins: "Побед игроков",
        admin_bot_wins: "Побед бота",
        admin_activity_title: "Активность (последние 24ч)",
        admin_recent_matches: "Последние матчи",
        admin_logs_title: "Логи админа",
        admin_view_profile: "Просмотр профиля",
        admin_matches: "матчей",
        admin_no_reason: "без причины",
        shop_title: "ТАКТИЧЕСКИЕ СПОСОБНОСТИ",
        ability_scout_title: "РАЗВЕДКА",
        ability_scout_desc: "Открыть 1 клетку",
        ability_scout_price: "40 монет",
        ability_sonar_title: "СОНАР",
        ability_sonar_desc: "Проверить зону 3x3",
        ability_sonar_price: "60 монет",
        ability_doubleShot_title: "ДВОЙНОЙ ВЫСТРЕЛ",
        ability_doubleShot_desc: "Два выстрела подряд",
        ability_doubleShot_price: "75 монет",
        ability_decoy_title: "ЛОЖНАЯ ЦЕЛЬ",
        ability_decoy_desc: "Следующий выстрел врага — мимо",
        ability_decoy_price: "50 монет",
        ability_radar_title: "РАДАР",
        ability_radar_desc: "Запрет повторных клеток",
        ability_radar_price: "70 монет",
        ability_overheat_title: "ПЕРЕГРЕВ",
        ability_overheat_desc: "Враг пропускает ход",
        ability_overheat_price: "120 монет",
        ability_fog_title: "ТУМАН",
        ability_fog_desc: "Скрыть часть поля",
        ability_fog_price: "80 монет",
        ability_counterStrike_title: "КОНТР-УДАР",
        ability_counterStrike_desc: "Ответный выстрел при попадании",
        ability_counterStrike_price: "95 монет",
        settings_title: "НАСТРОЙКИ",
        settings_lang_en: "Английский",
        settings_lang_ru: "Русский",
        error_save_user: "Ошибка сохранения. Проверьте интернет и откройте приложение снова.",
        error_create_battle: "Ошибка создания боя. Проверьте интернет.",
        error_matchmaking: "Ошибка матчмейкинга. Попробуйте позже.",
        match_finished: "Матч завершён",
        admin_done: "Готово!",
        shop_purchased: "Приобретено",
        shop_purchase_failed: "Ошибка покупки",
        matchmaking_search_title: "Ищем соперника...",
        matchmaking_search_sub: "Найдём честного врага или запустим бой с ботом.",
        matchmaking_cancel: "ОТМЕНА",
        matchmaking_vs_bot_easy: "Вы сражаетесь против бота (легко).",
        matchmaking_vs_bot_normal: "Вы сражаетесь против бота (нормально).",
        matchmaking_vs_bot_hard: "Вы сражаетесь против бота (сложно).",
        lb_title: "ТАБЛИЦЫ ЛИДЕРОВ",
        lb_tab_rating: "Рейтинг",
        lb_tab_winrate: "Винрейт 30+",
        lb_tab_games: "Игры",
        onboarding_slide1_title: "РАССТАНОВКА ФЛОТА",
        onboarding_slide1_text: "Расставьте свои корабли на поле. Нажмите на корабль, чтобы повернуть его. Когда все корабли расставлены, нажмите «К БОЮ».",
        onboarding_slide2_title: "ТАКТИЧЕСКИЕ СПОСОБНОСТИ",
        onboarding_slide2_text: "Покупайте способности в магазине за монеты. Используйте их в бою для получения преимущества: разведка, двойной выстрел, туман и другие.",
        onboarding_slide3_title: "РЕЙТИНГ И ЭКОНОМИКА",
        onboarding_slide3_text: "Выигрывайте матчи, чтобы повысить рейтинг и заработать монеты. Проигрывайте — теряйте рейтинг. Чем выше рейтинг, тем сильнее соперники.",
        onboarding_next: "ДАЛЕЕ",
        onboarding_skip: "ПРОПУСТИТЬ",
        onboarding_start: "НАЧАТЬ",
        error_low_rating: "Ваш рейтинг слишком низкий для рейтинговых матчей. Минимальный рейтинг: 25",
        error_low_rating_title: "Рейтинг слишком низкий"
    }
};
